name: Build Airflow Image

on:
  workflow_dispatch:
    inputs:
      target_app:
        description: "Target application, eg: airflow, backend"
        required: true
        type: choice
        options:
          - airflow
            backend

jobs:
  trigger-airflow-docker-build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Trigger docker build and promote to ecr
        env:
          GH_TOKEN: ${{ secrets.CICD_TRIGGER_TOKEN }}
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${GH_TOKEN}" \
            -H "X-GitHub-Api-Version: 2026-03-10" \
            https://api.github.com/repos/Housing-Intelligence/hi-platform-cicd/actions/workflows/docker-build-push-ecr.yml/dispatches \
            -d '{
              "ref": "main",
              "inputs": {
                "target_repository": "Housing-Intelligence/hi-app-terraforms",
                "docker_directory": "${{ inputs.target_app }}/docker",
                "aws_region": "us-east-2",
                "image_name": "${{ inputs.target_app }}"
              }
            }'
    
        